### ISSUE TITLE
trame CLI

### ISSUE THREAD

**Issue by banesullivan** [Kitware/trame#143]
Trame should have a CLI for more easily running scripts and for documenting the available options when running. I highly recommend gaining inspiration from `streamlit`'s CLI so that `trame` scripts do not have to have `__main__` catch and can have better support and auto refresh when running.

This would likely help with #119 

I don't think this would be a big ask as there is already args parsing happening.

**Comment by jourdain** [comment]
So is the only purpose of CLI to grab the server and call start() on it?

The auto-reload can work on a single file type of app with such CLI assuming there is no stateful behavior, but most of the time because trame is stateful it will not work and confuse people even more why it is not working.

For #119, that will not help at all since that is a client only problem. 

What do you mean by `documenting the available options when running`? Is the `--help` not working?

**Comment by jourdain** [comment]
The `export TRAME_HOT_RELOAD=1` or `server.hot_reload = True` can be use with `trame-server>=2.7.2` to handle dynamic reload of code without any custom CLI. The [hot_reload example](https://github.com/Kitware/trame/blob/master/examples/validation/core/17_hot_reload.py) provide enough background on how to use it.

**Comment by jourdain** [comment]
You can use `--hot-reload` as well...
