### ISSUE TITLE
Slicing function with trame

### ISSUE THREAD

**Issue by chiyandetaotie** [Kitware/trame#488]
Is there the Slicing function with trame? Is there any examples? I want to slice the unstructed grid with trame, how can I do?

**Comment by jourdain** [comment]
1. [Discussions](https://github.com/Kitware/trame/discussions) is a better place than Issues.
2. But since your question is related to VTK, the [VTK Discourse](https://discourse.vtk.org/) could be a better place for it.
3. [VTK has many examples, you should look at them first](https://examples.vtk.org/site/Python/).
