### ISSUE TITLE
How to deploy the trame application on the server

### ISSUE THREAD

**Issue by chiyandetaotie** [Kitware/trame#501]
I want to know how  to deploy the “trame” application on the server.I want to use "trame" as a post-processing module for the website. Does every user need to start a new "trame" service? Does each trame service need to occupy a different port? How to deploy it?

**Comment by jourdain** [comment]
We provide docker images that will allow you to bundle your trame app so you can serve multiple user automatically.

**Comment by jourdain** [comment]
Examples can be found in the [cookiecutter](https://github.com/Kitware/trame-cookiecutter) and [here](https://github.com/Kitware/trame/tree/master/examples/deploy/docker)

**Comment by chiyandetaotie** [comment]
In actual use, different users need to display different post-processing models and may perform different operations at the same time. I need to open an independent "trame" application for each user. There is no limit to the number of users who can log into the platform. How should I deploy it?

**Comment by jourdain** [comment]
Once you go with "no limit to the number of users at the same time", a single machine won't be enough and you need to start scaling dynamically based on the load. At that point, you need something like Kubernete or leverage an HPC. An option can be to look at a JupyterHub setup but with a trame app instead of a JupyterLab notebook.

If you want to work with Kitware to guide you through the specificities of your setup, you can reach out [here](https://www.kitware.com/contact).

**Comment by chiyandetaotie** [comment]
I donot know how to use "JupyterHub" or "Kubernete" to run "trame" independently for different users.
![image](https://github.com/Kitware/trame/assets/39592625/61502230-23fe-49ee-b6d4-bc66c34f1c9b)
I have submitted the form, but no one responded. Please tell me how to deploy it to meet my requirements.

**Comment by jourdain** [comment]
How long ago did you sent the request?

**Comment by chiyandetaotie** [comment]
2 days ago. And I have sent the request again, just now

**Comment by chiyandetaotie** [comment]
I try to use the "trame docker" to run the example (trame-master\examples\06_vtk\Applications\MultiFilter\app.py). 
The directory structure is as follows:
![image](https://github.com/Kitware/trame/assets/39592625/b931a60a-c07a-484b-a56d-f13c8cc1cd01)
 the apps.yml:
![image](https://github.com/Kitware/trame/assets/39592625/472e199a-b14f-4d10-8055-2c88d87eee6a)
the requirements:
![image](https://github.com/Kitware/trame/assets/39592625/aa9daff3-94eb-4988-86bd-66dd421a1b4f)
the Dockerfile:
![image](https://github.com/Kitware/trame/assets/39592625/f991c7e6-9b7f-4950-ad90-86bcc950e831)
but it has error as follows:
![image](https://github.com/Kitware/trame/assets/39592625/38e32ebe-f9e5-44bb-b9fd-f306a31b7112)
How should I solve this problem？

**Comment by jourdain** [comment]
You are not sharing the right log, but the issue is that you are running into is because you are using a regular vtk in and headless system (docker).
To solve that, you need to use `vtk-osmesa` or `vtk-egl` if you have an NVIDIA GPU and you are using docker with their runtime. See [Docker/EGL guide](https://kitware.github.io/trame/guide/deployment/docker.html) for more information.

You can find a VTK example with docker [here](https://github.com/Kitware/trame/tree/master/examples/deploy/docker/VtkRendering).
